### ISSUE TITLE
command 'projects.editConfig' not found 

### ISSUE THREAD

**Issue by gerhardcit** [fabiospampinato/vscode-projects-plus#10] opened 2017-11-13 06:53 UTC
In Vscode Version 1.19.0-insider (1.19.0-insider)

d6fbdcf19716910b26ea81efc95724f2fabe5aa6

None of the project commands work.

```command 'projects.switchGroup' not found```
```command 'projects.openInNewWindow' not found```

I removed the plugin, reinstalled it. Same thing.

It works fine in Version 1.18.0 (1.18.0)

dcee2202709a4f223185514b9275aa4229841aa7

**Comment by fabiospampinato** [comment] 2017-11-13 12:12
I can't reproduce this, it works fine for me using 1.19.0 (7a01db1b43a9c1df1cbb90dcf8ccdbaf33c90b6a).

Can you try updating to the latest build? If that doesn't fix it can you paste here your settings?

**Comment by aboukirev** [comment] 2018-03-08 21:52
Experienced this today.  I tracked it down to VSCode throwing "TypeError: Cannot delete read only property 'configPath' of object." internally.  I had 'proejcts.configPath' at default.  Once I added specific value in my personal settings for it and reloaded VSCode, everything worked.  My guess is that is because the setting does not have default configured in "contributes" section of "project.json" but I may be wrong.

**Comment by fabiospampinato** [comment] 2018-03-09 00:35
@aboukirev thanks for the info. What OS are you using? What VSC version? I need to reproduce this in order to fix it.

`proejcts.configPath`'s default is setted dynamically, that's why there's no default for it in `contributes`, maybe I could add a dummy one, but I don't see how that could be the problem.

**Comment by aboukirev** [comment] 2018-03-09 01:47
Windows 10 x64, Version 1.22.0-insider
Commit a9dcb2c3159367e347271d88c399e1f6ca88c23d
Date 2018-03-08T22:28:58.526Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

I simply opened Help -> Toggle Developer Tools and I could see the error in the Electron/Chrome console.  Apparently, it only shows there and does not propagate to VSCode output windows.

The message appears to be coming from the following fix: https://github.com/Microsoft/vscode/commit/98ef6607e69415c2b7acfbc25585911c18e85c03

**Comment by aboukirev** [comment] 2018-03-09 15:18
And it might have been just fixed in insiders by https://github.com/Microsoft/vscode/commit/24420491eb7a723d5ec6f6e0043f13ce259fb9ee

It is also about read-only property and they now clone target before attempting to delete or define property in configuration.

**Comment by fabiospampinato** [comment] 2018-03-12 12:48
@aboukirev I'm not sure this is related to @gerhardcit's original problem, so I'm going to keep this open. 

@gerhardcit Is it still not working for you on the latest stable release?

**Closed** 2018-04-27 18:03 UTC
