### ISSUE TITLE
Automatically add projects to groups, based on their path.

### ISSUE THREAD

**Issue by stefano-b** [fabiospampinato/vscode-projects-plus#62] opened 2020-04-14 15:42 UTC
Right now, when scanning for new projects, newly found ones are listed in the "no group" area in the UI, and I often need to rearrange them manually, even if they are somewhat already categorized by their location on my hard disk.

I'd like to be able to automatically place newly found project in a given group base on its path.

In example, let's assume that I place all my work projects in a `~/work` directory, and all my personal ones in `~/personal`, I'd like to be able to tell the extension somehow that `~/work/project-1`, `~/work/project-2`, `~/work/project-3` should be put in the `Work` group, while `~/personal/project-a`, `~/personal/project-b` and `~/personal/project-c` are instead expected to be placed in the `Personal` group.

Probably the easier way would be to add some settings (similar to the current "refresh roots" maybe?) where one can manually specify a path and a corresponding group to assign to the projects found inside it.

**Comment by fabiospampinato** [comment] 2020-04-14 16:08
Duplicate of https://github.com/fabiospampinato/vscode-projects-plus/issues/30

**Closed by fabiospampinato** 2020-04-14 16:08 UTC

**Comment by stefano-b** [comment] 2020-04-14 16:11
Yes, it seems to be similar, my proposal is less on a full automation road and more on manually defining pairs of "path + group", maybe it would be easier to implement.

**Comment by fabiospampinato** [comment] 2020-04-14 16:22
Maybe yeah. Let's talk about this over in the other issue, if you'd like to submit a PR for this we can talk more in detail about what an implementation for this could look like.
