### ISSUE TITLE
All project related commands "Not found"

### ISSUE THREAD

**Issue by AdamJacobson** [fabiospampinato/vscode-projects-plus#55] opened 2019-11-11 19:16 UTC
Started happening today.

All project related commands used via shortcuts or through the action menu return an error of not found
<img width="460" alt="Screen Shot 2019-11-11 at 11 12 34 AM" src="https://user-images.githubusercontent.com/7927980/68613856-8d350100-0474-11ea-8d02-70edf1c0ec07.png">

Have tried the following:
Disable and re-enable
Uninstall and re-install

VS Code version info:
```
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 16.7.0
```

**Comment by sangraal** [comment] 2019-11-11 22:41
Same problem here... 

See an error in the developer console that the extension is not activating.

```js
Activating extension 'fabiospampinato.vscode-projects-plus' failed: 'isExtensible' on proxy: trap result does not reflect extensibility of proxy target (which is 'true').
_logMessageInConsole @ abstractExtensionService.ts:396
```

**Comment by fabiospampinato** [comment] 2019-11-12 00:01
Duplicate of https://github.com/fabiospampinato/vscode-projects-plus/issues/51

**Closed by fabiospampinato** 2019-11-12 00:01 UTC
